enum HC05MODE { COMMUNICATION_MODE, AT_MODE }; //0,1 = LOW,HIGH
enum HC05ROLE { SLAVE, MASTER, SLAVE_LOOP };
enum HC05CMODE { CONNECT_BOUND, CONNECT_ANY, CONNECT_SLAVE_LOOP };
enum HC05STATE { DISCONNECTED, CONNECTED };

//possible states for the current program
enum ProgramState { //typedef not necessary in C++, only in C
  INITIALSTATECHECK,
  DO_ADCN,
  COUNTINGRECENTDEVICES,
  COUNTEDRECENTDEVICES,
  SEARCHAUTHENTICATEDDEVICE,
  CONNECTINGRECENTDEVICE,
  SETTINGCONNECTIONMODE,
  INITIATINGINQUIRY,
  INQUIRINGDEVICES,
  CONFRONTINGUSER,
  SETTINGBINDADDRESS,
  CONNECTINGTODEVICE,
  LISTENNMEA
};


